[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_swap_stake = "G5GVsUgjwXR9umkLDJcuweR2hUrnMnAFNWxv3DoRJ69b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/abhinawkumar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
